#!/bin/bash
#SBATCH --ntasks-per-node=4 
#SBATCH --mem 32000 # 32GB solicitados.
#SBATCH -p mlow # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir RTX 3090
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
python faster_rcnn.py

python3 detection.py -t faster-rcnn -b 0.9 -v /ghome/c3mcv02/mcv-c6-2025-team1/data/AICity_data/train/S03/c010/vdo.avi -a /ghome/c3mcv02/mcv-c6-2025-team1/data/ai_challenge_s03_c010-full_annotation.xml -o test_out.avi