#!/bin/bash
#SBATCH --ntasks-per-node=4 
#SBATCH --mem=50000  # 50GB de RAM sol·licitats.
#SBATCH -p mlow  # Partició de màxima prioritat (o canvia a mlow si ho prefereixes)
#SBATCH --gres=gpu:1  # Demanar una GPU RTX 3090
#SBATCH -o %x_%u_%j.out  # Fitxer per la sortida STDOUT
#SBATCH -e %x_%u_%j.err  # Fitxer per la sortida STDERR

# Definició de variables
VIDEO_PATH="/ghome/c3mcv02/mcv-c6-2025-team1/data/AICity_data/train/S03/c010/vdo.avi"
ANNOTATIONS_PATH="/ghome/c3mcv02/mcv-c6-2025-team1/data/ai_challenge_s03_c010-full_annotation.xml"
AREA_THRESHOLD=918
ASPECT_RATIO=2.1155
OPENING_SIZE=3
CLOSING_SIZE=13
OUTPUT_DIR="output_videos_adaptive"

# Crear la carpeta de sortida si no existeix
mkdir -p $OUTPUT_DIR

# Iterar per diferents valors d'alpha
for ALPHA in 3.5
do
    OUTPUT_VIDEO="${OUTPUT_DIR}/output_alpha_${ALPHA}.avi"
    MASK_VIDEO="${OUTPUT_DIR}/mask_alpha_${ALPHA}.avi"

    echo "Running with alpha=$ALPHA..."
    python main_adaptive.py -v=$VIDEO_PATH -a=$ALPHA -t=$AREA_THRESHOLD --annotations=$ANNOTATIONS_PATH --use_median --opening_size=$OPENING_SIZE --closing_size=$CLOSING_SIZE -r=$ASPECT_RATIO -o=$OUTPUT_VIDEO -m=$MASK_VIDEO
done

echo "Tots els vídeos s'han guardat a la carpeta $OUTPUT_DIR"
